CREATE DATABASE [DealDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DealDB', FILENAME = N'C:\Users\akopi\DealDB.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DealDB_log', FILENAME = N'C:\Users\akopi\DealDB_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [DealDB] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [DealDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DealDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DealDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DealDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DealDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [DealDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DealDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DealDB] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [DealDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DealDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DealDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DealDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DealDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DealDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DealDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DealDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DealDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DealDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DealDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DealDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DealDB] SET  READ_WRITE 
GO
ALTER DATABASE [DealDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DealDB] SET  MULTI_USER 
GO
ALTER DATABASE [DealDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DealDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DealDB] SET DELAYED_DURABILITY = DISABLED 
GO
USE [DealDB]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [DealDB]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [DealDB] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
